# Generated by Django 5.1.2 on 2024-11-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Name', models.CharField(max_length=10)),
                ('Accno', models.IntegerField(primary_key='accno', serialize=False)),
                ('Email', models.EmailField(max_length=254)),
                ('Dob', models.DateField()),
                ('Adharno', models.IntegerField()),
            ],
        ),
    ]
